name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create data asset
      run: az ml data create --name diabetes-dev-folder --version 1 --path ./experimentation/data -w mlw-ml-${{ vars.RANDOM_PET_SUFFIX }} -g rg-ml-${{ vars.RANDOM_PET_SUFFIX }}
    - name: Create a job
      run: |
        # replace compute name variable
        export computeName=${{ vars.computeClusterName }}
        cat src/job.yml | envsubst | tee job-updated.yml
        # create a job
        az ml job create --file job-udpated.yml -w mlw-ml-${{ vars.RANDOM_PET_SUFFIX }} -g rg-ml-${{ vars.RANDOM_PET_SUFFIX }}
