name: Manually trigger an Azure Machine Learning job

on:
  pull-request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  demo:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
